[package]
name = "c2-chacha"
version = "0.1.0"
authors = ["The CryptoCorrosion Contributors"]
license = "MIT/Apache-2.0"
edition = "2018"
description = "The ChaCha family of stream ciphers"
repository = "https://github.com/cryptocorrosion/cryptocorrosion"
keywords = ["chacha", "chacha20", "xchacha20", "chacha12", "chacha8", "cipher", "crypto"]
categories = ["cryptography", "no-std"]

[dependencies]
byteorder = "1.3"
crypto-simd = "0.1"
packed_simd_crate = { package = "packed_simd", version = "0.3.2", optional = true }
ppv-null = "0.1.1"
simd = { package = "ppv-lite86", version = "0.1.1", optional = true }
stream-cipher = "0.3"

[dev-dependencies]
hex-literal = "0.1"

[features]
default = ["simd", "std"]
std = []
packed_simd = ["packed_simd_crate", "crypto-simd/packed_simd"]

[badges]
travis-ci = { repository = "cryptocorrosion/cryptocorrosion" }
