[package]
name = "blake-hash"
version = "0.3.1"
authors = ["The CryptoCorrosion Contributors"]
license = "MIT/Apache-2.0"
description = "BLAKE hash functions"
repository = "https://github.com/cryptocorrosion/cryptocorrosion"
keywords = ["crypto", "blake", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
block-buffer = "0.7"
crypto-simd = "0.1"
digest = "0.8"
packed_simd_crate = { package = "packed_simd", version = "0.3.2", optional = true }
simd = { package = "ppv-lite86", version = "0.1.0", optional = true }
ppv-null = "0.1"

[features]
default = ["simd", "std"]
std = []
packed_simd = ["packed_simd_crate", "crypto-simd/packed_simd"]

[dev-dependencies]
digest = { version = "0.8", features = ["dev"] }

[badges]
travis-ci = { repository = "cryptocorrosion/cryptocorrosion" }
